jobs:
  - template: build.yml
  - job: signing_area
    dependsOn: python_build
    displayName: Signing Test Area
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - download: current
        patterns: '**/*.whl'
      - script: |
          set -x
          mkdir wheels
          find $(Pipeline.Workspace) -name *.whl -print0 | xargs -I % -0 mv -v % wheels/
#          ls -ahl wheels
#          cd wheels
#          find . -name '*.whl' -print0 | xargs -I % -0 unzip -d %_unzipped %
#          ls -ahlR
        displayName: "Unpack and sign and stuff"
      - task: EsrpCodeSigning@1
        inputs:
          ConnectedServiceName: 'ESRP Code Signing Service Connection'
          FolderPath: '$(Pipeline.Workspace)/wheels/'
          Pattern: '*.whl'
          signConfigType: 'inlineSignParams'
          inlineOperation: |
            [
              {
                "keyCode": "CP-231522",
                "operationSetCode": "SigntoolSign",
                "parameters": [
                  {
                    "parameterName": "OpusName",
                    "parameterValue": "Microsoft"
                  },
                  {
                    "parameterName": "OpusInfo",
                    "parameterValue": "http://www.microsoft.com"
                  },
                  {
                    "parameterName": "Append",
                    "parameterValue" : "/as",
                  },
                  {
                    "parameterName": "PageHash",
                    "parameterValue": "/NPH"
                  },
                  {
                    "parameterName": "FileDigest",
                    "parameterValue": "/fd sha256"
                  },
                  {
                    "parameterName": "TimeStamp",
                    "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                  }
                ],
                "toolName": "signtool.exe",
                "toolVersion": "6.2.9304.0"
              }
            ]
          SessionTimeout: '60'
          MaxConcurrency: '50'
          MaxRetryAttempts: '5'
