[package]
name = "cli"
version = "0.1.0"
authors = ["Dwayne Pryce <dwpryce@microsoft.com>"]
edition = "2018"
license = "MIT"
description = "CLI Runner for the topologic associated crates (network_partitions and eventually network_automatic_layouts)"

[dependencies]
clap = "2.33"
rand = "0.7"
rand_xorshift = "0.2"
network_partitions={path = "../network_partitions"}

[features]
logging = ["network_partitions/logging"]
